// <auto-generated />
using System;
using DotNetPlayground.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetPlayground.Migrations
{
    [DbContext(typeof(Baza))]
    [Migration("20230118135741_dodanaOsoba")]
    partial class dodanaOsoba
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("DotNetPlayground.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatumKreiranja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumKreiranja = "09.01.2023",
                            Marka = "Audi",
                            Tip = "Karavan"
                        },
                        new
                        {
                            Id = 2,
                            DatumKreiranja = "09.01.2023",
                            Marka = "Škoda",
                            Tip = "Limuzina"
                        },
                        new
                        {
                            Id = 3,
                            DatumKreiranja = "09.01.2023",
                            Marka = "Toyota",
                            Tip = "Džip"
                        },
                        new
                        {
                            Id = 4,
                            DatumKreiranja = "09.01.2023",
                            Marka = "VW",
                            Tip = "SUV"
                        });
                });

            modelBuilder.Entity("DotNetPlayground.Models.Maca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Godine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vrsta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mace");
                });

            modelBuilder.Entity("DotNetPlayground.Models.Osoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DatumKreiranja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumRodjenja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NajdrazaHrana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Osoba");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumKreiranja = new DateTime(2023, 1, 18, 14, 57, 41, 591, DateTimeKind.Local).AddTicks(7671),
                            DatumRodjenja = new DateTime(1995, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amor@gmx.com",
                            Ime = "Amor",
                            NajdrazaHrana = "Krompir",
                            Prezime = "Osmić"
                        },
                        new
                        {
                            Id = 2,
                            DatumKreiranja = new DateTime(2023, 1, 18, 14, 57, 41, 591, DateTimeKind.Local).AddTicks(7707),
                            DatumRodjenja = new DateTime(1995, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@gmx.com",
                            Ime = "Sara",
                            NajdrazaHrana = "Pizza",
                            Prezime = "Šahinpašić"
                        },
                        new
                        {
                            Id = 3,
                            DatumRodjenja = new DateTime(1998, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ines@gmx.com",
                            Ime = "Ines",
                            NajdrazaHrana = "Špagete",
                            Prezime = "Osmić"
                        },
                        new
                        {
                            Id = 4,
                            DatumRodjenja = new DateTime(1994, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jasko@gmx.com",
                            Ime = "Jasko",
                            NajdrazaHrana = "Burek",
                            Prezime = "Kreho"
                        });
                });

            modelBuilder.Entity("DotNetPlayground.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FavouriteFood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavouriteFood = "Krompir",
                            FirstName = "Amor",
                            LastName = "Osmić"
                        },
                        new
                        {
                            Id = 2,
                            FavouriteFood = "Pizza",
                            FirstName = "Sara",
                            LastName = "Šahinpašić"
                        },
                        new
                        {
                            Id = 3,
                            FavouriteFood = "Špagete",
                            FirstName = "Ines",
                            LastName = "Osmić"
                        },
                        new
                        {
                            Id = 4,
                            FavouriteFood = "Burek",
                            FirstName = "Jasko",
                            LastName = "Kreho"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
